export const INIT_CV = 'INIT_CV'

export const EDIT_PERSONALINFO = "EDIT_PERSONALINFO"

export const EDIT_EDUCATION = "EDIT_EDUCATION"
export const ADD_EDUCATION = "ADD_EDUCATION"
export const DELETE_EDUCATION = "DELETE_EDUCATION"

export const EDIT_EXPERIECE = "EDIT_EXPERIECE"
export const ADD_EXPERIECE = "ADD_EXPERIECE"
export const DELETE_EXPERIECE = "DELETE_EXPERIECE"

export const EDIT_SKILL = "EDIT_SKILL"
export const ADD_SKILL = "ADD_SKILL"
export const DELETE_SKILL = "DELETE_SKILL"
 
